### ISSUE TITLE
Issue when downloading and parsing DAM_AggDemandSupplyCurves

### ISSUE THREAD

**Issue by IvnSmgh** [ThanosGkou/exso#2]
Hi Thano,

First of all, what amazing work you've done here. I cannot thank you enough. I'm having an issue when first doing the Basic Update. Once the update reached DAM_AggDemandSuppluCurves, I get the following error 

`--> ParsingError. See logs.
Traceback (most recent call last):
  File "C:\Users\Nicolas.Kyriakoglou\git\exso\venv\Lib\site-packages\exso\DataLake\Parsers\ParsersArch.py", line 21, in wrap
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nicolas.Kyriakoglou\git\exso\venv\Lib\site-packages\exso\DataLake\Parsers\ParsersArch.py", line 122, in pipe
    df = self.pre_proc(df)
         ^^^^^^^^^^^^^^^^^
  File "C:\Users\Nicolas.Kyriakoglou\git\exso\venv\Lib\site-packages\exso\DataLake\Parsers\ParsersVerticalLong.py", line 427, in pre_proc
    df = pd.pivot_table(df, index=self.index_cols, columns=self.eigen_cols, values=self.payload_cols)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nicolas.Kyriakoglou\git\exso\venv\Lib\site-packages\pandas\core\reshape\pivot.py", line 102, in pivot_table
    table = __internal_pivot_table(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nicolas.Kyriakoglou\git\exso\venv\Lib\site-packages\pandas\core\reshape\pivot.py", line 148, in __internal_pivot_table
    raise KeyError(i)
KeyError: 'QUANTITY'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\Nicolas.Kyriakoglou\git\exso\venv\Lib\site-packages\exso\DataLake\Parsers\ParsersArch.py", line 32, in wrap
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nicolas.Kyriakoglou\git\exso\venv\Lib\site-packages\exso\DataLake\Parsers\ParsersArch.py", line 122, in pipe
    df = self.pre_proc(df)
         ^^^^^^^^^^^^^^^^^
  File "C:\Users\Nicolas.Kyriakoglou\git\exso\venv\Lib\site-packages\exso\DataLake\Parsers\ParsersVerticalLong.py", line 427, in pre_proc
    df = pd.pivot_table(df, index=self.index_cols, columns=self.eigen_cols, values=self.payload_cols)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nicolas.Kyriakoglou\git\exso\venv\Lib\site-packages\pandas\core\reshape\pivot.py", line 102, in pivot_table
    table = __internal_pivot_table(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nicolas.Kyriakoglou\git\exso\venv\Lib\site-packages\pandas\core\reshape\pivot.py", line 148, in __internal_pivot_table
    raise KeyError(i)
KeyError: 'QUANTITY'
Process finished with exit code 0`

When debugging, it seems that the update is reading DAM/LIDA/CRIDA files instead of AggDemandSuppyCurves files when doing the DAM_AggDemandSupplyCurves update. And the errors occurs, it seems, because the parser class that is being called from ParsersVerticalLong.py is the DAM_AggDemandSupplyCurves class instead of the DAM_Results class, causing the operation to fail.

Apologies if I'm not describing this adequately, I have very limited coding training!

Thanks!

**Comment by IvnSmgh** [comment]
Actually I'm seeing now that when the datalake is create, all DAM/LIDA/CRIDA/XBID results and all AggCurves are placed into the same folder name DAM_AggDemandSupplyCurves

**Comment by IvnSmgh** [comment]
Issue was resolved by deleting the henex folder in the destination path and re-running the update.

**Comment by ThanosGkou** [comment]
Hi and thanks for your interest. Good to hear the issue was resolved, good thinking deleting the folder.
